version: "3"

services:
  kong-database:
    image: cassandra:3
    container_name: kong-database
    ports:
      - 7000:7000
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  kong:
    image: kong:2.0.2-alpine
    container_name: kong
    restart: on-failure
    depends_on:
      - kong-database
    links:
      - kong-database:kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    environment:
      - KONG_DATABASE=cassandra
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl

networks:
  default:
    external:
      name: onsite-net
